export const state = {
	mode: "6-bit",
	bitOrientation: "vertical",
	show24HourFormat: false,
	helpVisible: false,
	digitalVisible: true,
	digitalVisibleBeforeHelp: null,
	scanlinesVisible: true,
	lsbFirst: false,
	autoOrient: true,
	theme: "classic-rgb-neon",
	randomMode: false,
	randomThemeIntervalId: null,
	modeTransitioning: false,
	transitionTargetMode: null,
	transitionTimeoutId: null,
	transitionArmId: null,
	transitionActivateId: null,
	themeMotionTimeoutId: null,
	orientationTransitionTimeoutId: null,
	orientationTransitionArmId: null,
	orientationTransitionActivateId: null,
	pendingTick: null,
	intervalId: null,
	// Game mode state
	gameMode: null, // null | "bit-clicking" | "quiz"
	gameActive: false,
	gameScore: 0,
	gameLevel: 1,
	gameQuestionsAnswered: 0,
	gameStreak: 0,
	gameTimerSeconds: 0,
	gameDifficulty: "normal", // normal, hard
	gameTargetValue: 0,
	quizTimeRemaining: 0
};
